import { z } from "zod";

export const ContratosSchemaTypeSchema = z.array(
	z.object({
		CODIGO: z.string(),
		ANO: z.string(),
		FUNDLEGAL: z.string(),
		LICIT: z.string(),
		PROCLIC: z.string(),
		MODALI: z.string(),
		NUMLICMOD: z.string(),
		NPROLI: z.string(),
		FORNECEDOR: z.string(),
		VALCON: z.string(),
		DTASSI: z.string(),
		TIPOCO: z.string(),
		REGEXE: z.string(),
		GARANT: z.string(),
		VIGENI: z.string(),
		VIGENF: z.string(),
		RESPON: z.string(),
		RESPON_DOC: z.string(),
		OBJETO_COMPLETO: z.string(),
		OBJETO: z.string(),
		NUMOBRA: z.string(),
		ENTIDADE: z.string(),
		TIPOCOOBRA: z.string(),
		BALCO_DEBITO: z.string(),
		CPFTRA: z.string(),
		CPFLEG: z.string(),
		CONTRATONUM: z.string(),
		MULTA_RESCISORIA: z.string(),
		MULTA_INADIMPLENCIA: z.string(),
		EMPENHADOANT: z.string(),
		EMPENHADO: z.string(),
		LIQUIDADOANT: z.string(),
		LIQUIDADO: z.string(),
		ADITADO: z.string(),
		SALDOEMPENHAR: z.string(),
		SALDOLIQUIDAR: z.string(),
		NUMLIC: z.string(),
		EMPRESA: z.string(),
		CODTCE: z.string(),
		INSMF: z.string(),
		RESPON2: z.string(),
		DTPUBL: z.string(),
		CODLO_GESTOR: z.string(),
		CODLO_GESTORNOME: z.string(),
		DTPUB: z.string(),
		VENCIMENTO_ATUAL: z.string(),
		DTANULA: z.string(),
		TIPOANU: z.string(),
	}),
);

export type ContratosSchemaTypeSchemaType = z.infer<
	typeof ContratosSchemaTypeSchema
>;
